# Generated by Django 4.0 on 2021-12-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('UserDrawnPicture', models.ImageField(upload_to='images')),
                ('UserTakenPicture', models.ImageField(upload_to='images')),
                ('FirstTravel', models.CharField(max_length=200)),
                ('FirstTravelRate', models.CharField(max_length=200)),
                ('SecondTravel', models.CharField(max_length=200)),
                ('SecondTravelRate', models.CharField(max_length=200)),
                ('ThirdTravel', models.CharField(max_length=200)),
                ('ThirdTravelRate', models.CharField(max_length=200)),
                ('FindDateTime', models.DateTimeField(auto_now=True)),
                ('Destination_choice', models.CharField(choices=[('MT', 'Mountain'), ('OC', 'Ocean'), ('LM', 'LandMark'), ('PL', 'Plain')], max_length=2)),
            ],
            options={
                'ordering': ['-FindDateTime'],
            },
        ),
    ]
