# Generated by Django 4.0 on 2021-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='FirstTravel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='FirstTravelRate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='SecondTravel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='SecondTravelRate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='ThirdTravel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='ThirdTravelRate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='UserDrawnPicture',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='UserTakenPicture',
            field=models.ImageField(blank=True, upload_to='image/taken'),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
