# Generated by Django 4.0 on 2021-12-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTproject', '0002_alter_userpicture_firsttravel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='UserDrawnPicture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='UserTakenPicture',
            field=models.ImageField(blank=True, upload_to='taken'),
        ),
    ]
