# Generated by Django 4.0 on 2021-12-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTproject', '0003_alter_userpicture_userdrawnpicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='UserDrawnPicture',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='UserTakenPicture',
            field=models.ImageField(blank=True, upload_to='image/taken'),
        ),
    ]
