# Generated by Django 4.0 on 2021-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTproject', '0005_alter_userpicture_usertakenpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='UserDrawnPicture',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='UserTakenPicture',
            field=models.ImageField(blank=True, null=True, upload_to='taken/'),
        ),
    ]
